apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountant-deployment
  labels:
    app: accountant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accountant
  template:
    metadata:
      labels:
        app: accountant
    spec:
      containers:
        - name: accountant
          image: ischepov/accountant:latest
          ports:
            - containerPort: 8081